language: node_js
node_js:
  - "6.14.0"
services:
  - postgresql
before_script:
  - psql -c 'create database ci;' -U postgres
  - export PGHOST=localhost
  - export PGDATABASE=ci
  - export PGUSER=postgres
  - export PGPASSWORD=
